### ISSUE TITLE
How do you create the mention_type_test.txt?

### ISSUE THREAD

**Issue by 33Peng33** [shanzhenren/CoType#8]
I tried to run ./run.sh but it didn't create mention_type_test.txt  I get this:

Traceback (most recent call last):
  File "code/Evaluation/convertPredictionToJson.py", line 13, in <module>
    with open(typeMapFile) as typeF:
IOError: [Errno 2] No such file or directory: 'data/intermediate/KBP/rm/type.txt'
Traceback (most recent call last):
  File "code/Evaluation/tune_threshold.py", line 66, in <module>
    ground_truth = load_labels(indir + '/mention_type_test.txt')
  File "/workspace/png/CoType-master/code/Evaluation/evaluation.py", line 17, in load_labels
    with open(file_name) as f:
IOError: [Errno 2] No such file or directory: 'data/intermediate/KBP/rm/mention_type_test.txt'

**Comment by ellenmellon** [comment]
It seems like you didn't generate intermediate files properly... They should be generated in the feature generation pipeline.
